/*
  
 File: ErrorHandling.h
 Abstract: Contains constants used for error handling. 
 
*/


#import <Foundation/Foundation.h>

#define ERROR_DOMAIN @"SAP Netweaver Gateway Service Proxy"
#define SCHEMA_ERROR_CODE 1001
#define RESPONSE_PARSER_ERROR_CODE 1002
#define SDM_ENTRY_INVALID_ERROR_CODE 1003
#define SDM_ENTRY_PROPERTY_VALUE_ERROR_CODE 1004
#define SDM_ENTRY_XML_BUILDER_ERROR_CODE 1005
#define SERVICE_URL_EMPTY_ERROR_CODE 1006
#define LOGIN_ERROR_CODE 1007
#define SERVICE_METADATA_PARSE_ERROR_CODE 1008
#define SERVICE_NEGOTIATION_ERROR_CODE 1010
#define REQUEST_FAILED_ERROR_CODE 1011
#define CERTIFICATE_HANDLING_ERROR_CODE 1012