/*
 
 Auto-Generated by SAP NetWeaver Gateway Productivity Accelerator, Version 1.0
 
 File: sapsopaServiceV0.h
 Abstract: The generated proxy classes for the sapsopa Service.   
*/

#import <Foundation/Foundation.h>
#import "BaseEntityType.h"
#import "BaseComplexType.h"
#import "BaseServiceObject.h"

#pragma mark - Complex Types



#pragma mark - Entity Types

/**
 Each of the following classes represents an entity-type of the sapsopaServiceV0 service.
 
 Any entity-type class should be used as following:
 
 1. The entity object may represent an existing entry of an appropriate service collection,
 if the object is initialized using data returned from an appropriate service call.
 This may be achieved by using the initWithSDMEntry: constructor,
 or using the static methods creating the entity object (parse<entity-type-name>EntriesWithData,
 parse<entity-type-name>EntryWithData, and create<entity-type-name>EntriesForSDMEntries).
 
 For retrieving the entry data, use the appropriate query properties and methods of this class 
 and of the sapsopaServiceV0 class, and then execute the request (see the SDMConnectivityHelper class).
 
 2. Another option is to use this entity object as a new entry to create in an appropriate service collection.
 In this case, use the init constructor and set the appropriate properties. 
 Note that some features (as navigation properties) are not available in this mode (since it is not yet an actual service entry).
 Use the SDMConnectivityHelper class and the getXMLForCreateRequest method of the BaseServiceObject class, to send the 'create' request.
 Then use the service response for constructing a new object, in order to represent the entry as existed in the service. 
 
 In both operation modes, setting the entity property values will not affect the service until the changes are sent to the server.
 For sending changes to the server, see the SDMConnectivityHelper class and the getXMLForRequest methods of the BaseServiceObject class.
 It is recommended to use the server response for constructing a new object, in order to represent the entry as existed in the service.
 
 Note: For proper behavior of this class, make sure to initialize the sapsopaServiceV0 class
 in your application, before initializing the entity-type class objects.
*/
 

#pragma mark - reportsTypeV0
@interface reportsTypeV0 : BaseEntityType 

@property (strong, nonatomic) NSString *REPORTID; ///< REPORTID - Edm.String
@property (strong, nonatomic) NSString *REPORTNAME; ///< REPORTNAME - Edm.String
@property (strong, nonatomic) NSString *REPORTDESCR; ///< REPORTDESCR - Edm.String
@property (strong, nonatomic) NSString *ISMOBILEENABLED; ///< ISMOBILEENABLED - Edm.String
@property (strong, nonatomic) NSString *CREATEDBY; ///< CREATEDBY - Edm.String
@property (strong, nonatomic) NSDate *CREATEDDATE; ///< CREATEDDATE - Edm.DateTime
@property (strong, nonatomic) NSDate *LASTMODIFIEDDATE; ///< LASTMODIFIEDDATE - Edm.DateTime
@property (strong, nonatomic) NSString *LASTMODIFIEDBY; ///< LASTMODIFIEDBY - Edm.String
#pragma mark Entity Navigation Properties
@property (strong, nonatomic) ODataQuery *reportQuery;
@property (strong, nonatomic) NSMutableArray *report;

#pragma mark Static Methods
/**
 Static method that returns an array of reportsTypeV0 entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to reportsTypeV0 entities.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of reportsTypeV0 entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseReportsTypeEntriesWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of reportsTypeV0 entities and their related entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to reportsTypeV0 entities.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of reportsTypeV0 entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseExpandedReportsTypeEntriesWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Returns a single reportsTypeV0 entity from the provided data.
 @param aData The NSData containing an Atom Entry including the entry to be parsed to a reportsTypeV0 entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a reportsTypeV0 entity. Returns nil if the data in invalid.
*/
+ (reportsTypeV0 *)parseReportsTypeEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns a single reportsTypeV0 entity and related entities from the provided data.
 @param aData The NSData containing an Atom Entry including the entry and its related entries to be parsed to a reportsTypeV0 entity.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a reportsTypeV0 entity. Returns nil if the data in invalid.
*/
+ (reportsTypeV0 *)parseExpandedReportsTypeEntryWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of reportsTypeV0 objects from a given array of SDMODataEntry objects.
 @param sdmEntries Array of SDMODataEntry objects.
 @return Array of reportsTypeV0 objects.
*/
+ (NSMutableArray *)createReportsTypeEntriesForSDMEntries:(NSMutableArray *)sdmEntries;

/**
 Static method that loads the entity schema of this type.
 This method is called when the sapsopaServiceV0 class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadEntitySchema:(SDMODataServiceDocument *)aService;

/**
 Static method that loads all of the entity type property labels.
 This method is called when the sapsopaServiceV0 class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadLabels:(SDMODataServiceDocument *)aService;

/**
 Static method that returns the label for a given property name.
 @param aPropertyName Property name.
 @return Property label.
*/
+ (NSString *)getLabelForProperty:(NSString *)aPropertyName;


#pragma mark Entity Navigation Property loading methods
/**
 Navigation property. Loads report details for this entity from the provided data.
 @param aData The NSData containing the report information to be parsed.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns YES if the method completed successfully.
*/
- (BOOL)loadReportWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;


@end

#pragma mark - reportpagesTypeV0
@interface reportpagesTypeV0 : BaseEntityType 

@property (strong, nonatomic) NSString *REPORTPAGEID; ///< REPORTPAGEID - Edm.String
@property (strong, nonatomic) NSString *REPORTPAGENAME; ///< REPORTPAGENAME - Edm.String
@property (strong, nonatomic) NSString *REPORTPAGEDESCR; ///< REPORTPAGEDESCR - Edm.String
@property (strong, nonatomic) NSString *ISOWNER; ///< ISOWNER - Edm.String
@property (strong, nonatomic) NSString *ISMOBILEENABLED; ///< ISMOBILEENABLED - Edm.String
@property (strong, nonatomic) NSString *LAYOUTID; ///< LAYOUTID - Edm.String
@property (strong, nonatomic) NSNumber *NUMBEROFROWS; ///< NUMBEROFROWS - Edm.Byte
@property (strong, nonatomic) NSNumber *NUMBEROFCOLUMNS; ///< NUMBEROFCOLUMNS - Edm.Byte
@property (strong, nonatomic) NSString *ROWHEIGHT; ///< ROWHEIGHT - Edm.String
@property (strong, nonatomic) NSString *COLUMNWIDTH; ///< COLUMNWIDTH - Edm.String
@property (strong, nonatomic) NSString *CREATEDBY; ///< CREATEDBY - Edm.String
@property (strong, nonatomic) NSDate *CREATEDDATE; ///< CREATEDDATE - Edm.DateTime
@property (strong, nonatomic) NSDate *LASTMODIFIEDDATE; ///< LASTMODIFIEDDATE - Edm.DateTime
@property (strong, nonatomic) NSString *LASTMODIFIEDBY; ///< LASTMODIFIEDBY - Edm.String
#pragma mark Entity Navigation Properties
@property (strong, nonatomic) ODataQuery *reportpagelayoutQuery;
@property (strong, nonatomic) NSMutableArray *reportpagelayout;

#pragma mark Static Methods
/**
 Static method that returns an array of reportpagesTypeV0 entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to reportpagesTypeV0 entities.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of reportpagesTypeV0 entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseReportpagesTypeEntriesWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of reportpagesTypeV0 entities and their related entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to reportpagesTypeV0 entities.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of reportpagesTypeV0 entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseExpandedReportpagesTypeEntriesWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Returns a single reportpagesTypeV0 entity from the provided data.
 @param aData The NSData containing an Atom Entry including the entry to be parsed to a reportpagesTypeV0 entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a reportpagesTypeV0 entity. Returns nil if the data in invalid.
*/
+ (reportpagesTypeV0 *)parseReportpagesTypeEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns a single reportpagesTypeV0 entity and related entities from the provided data.
 @param aData The NSData containing an Atom Entry including the entry and its related entries to be parsed to a reportpagesTypeV0 entity.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a reportpagesTypeV0 entity. Returns nil if the data in invalid.
*/
+ (reportpagesTypeV0 *)parseExpandedReportpagesTypeEntryWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of reportpagesTypeV0 objects from a given array of SDMODataEntry objects.
 @param sdmEntries Array of SDMODataEntry objects.
 @return Array of reportpagesTypeV0 objects.
*/
+ (NSMutableArray *)createReportpagesTypeEntriesForSDMEntries:(NSMutableArray *)sdmEntries;

/**
 Static method that loads the entity schema of this type.
 This method is called when the sapsopaServiceV0 class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadEntitySchema:(SDMODataServiceDocument *)aService;

/**
 Static method that loads all of the entity type property labels.
 This method is called when the sapsopaServiceV0 class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadLabels:(SDMODataServiceDocument *)aService;

/**
 Static method that returns the label for a given property name.
 @param aPropertyName Property name.
 @return Property label.
*/
+ (NSString *)getLabelForProperty:(NSString *)aPropertyName;


#pragma mark Entity Navigation Property loading methods
/**
 Navigation property. Loads reportpagelayout details for this entity from the provided data.
 @param aData The NSData containing the reportpagelayout information to be parsed.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns YES if the method completed successfully.
*/
- (BOOL)loadReportpagelayoutWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;


@end

#pragma mark - reportviewsTypeV0
@interface reportviewsTypeV0 : BaseEntityType 

@property (strong, nonatomic) NSString *REPORTVIEWID; ///< REPORTVIEWID - Edm.String
@property (strong, nonatomic) NSString *REPORTVIEWNAME; ///< REPORTVIEWNAME - Edm.String
@property (strong, nonatomic) NSString *REPORTVIEWDESCR; ///< REPORTVIEWDESCR - Edm.String
@property (strong, nonatomic) NSString *REPORTVIEWTYPE; ///< REPORTVIEWTYPE - Edm.String
@property (strong, nonatomic) NSString *ISOWNER; ///< ISOWNER - Edm.String
@property (strong, nonatomic) NSString *ISMOBILEENABLED; ///< ISMOBILEENABLED - Edm.String
@property (strong, nonatomic) NSString *REPORTID; ///< REPORTID - Edm.String
@property (strong, nonatomic) NSString *DISPLAYLEGEND; ///< DISPLAYLEGEND - Edm.String
@property (strong, nonatomic) NSString *LEGENDPOSITION; ///< LEGENDPOSITION - Edm.String
@property (strong, nonatomic) NSString *CREATEDBY; ///< CREATEDBY - Edm.String
@property (strong, nonatomic) NSDate *CREATEDDATE; ///< CREATEDDATE - Edm.DateTime
@property (strong, nonatomic) NSDate *LASTMODIFIEDDATE; ///< LASTMODIFIEDDATE - Edm.DateTime
@property (strong, nonatomic) NSString *LASTMODIFIEDBY; ///< LASTMODIFIEDBY - Edm.String
#pragma mark Entity Navigation Properties
@property (strong, nonatomic) ODataQuery *reportviewQuery;
@property (strong, nonatomic) NSMutableArray *reportview;
@property (strong, nonatomic) ODataQuery *reportviewfiltersQuery;
@property (strong, nonatomic) NSMutableArray *reportviewfilters;

#pragma mark Static Methods
/**
 Static method that returns an array of reportviewsTypeV0 entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to reportviewsTypeV0 entities.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of reportviewsTypeV0 entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseReportviewsTypeEntriesWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of reportviewsTypeV0 entities and their related entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to reportviewsTypeV0 entities.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of reportviewsTypeV0 entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseExpandedReportviewsTypeEntriesWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Returns a single reportviewsTypeV0 entity from the provided data.
 @param aData The NSData containing an Atom Entry including the entry to be parsed to a reportviewsTypeV0 entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a reportviewsTypeV0 entity. Returns nil if the data in invalid.
*/
+ (reportviewsTypeV0 *)parseReportviewsTypeEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns a single reportviewsTypeV0 entity and related entities from the provided data.
 @param aData The NSData containing an Atom Entry including the entry and its related entries to be parsed to a reportviewsTypeV0 entity.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a reportviewsTypeV0 entity. Returns nil if the data in invalid.
*/
+ (reportviewsTypeV0 *)parseExpandedReportviewsTypeEntryWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of reportviewsTypeV0 objects from a given array of SDMODataEntry objects.
 @param sdmEntries Array of SDMODataEntry objects.
 @return Array of reportviewsTypeV0 objects.
*/
+ (NSMutableArray *)createReportviewsTypeEntriesForSDMEntries:(NSMutableArray *)sdmEntries;

/**
 Static method that loads the entity schema of this type.
 This method is called when the sapsopaServiceV0 class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadEntitySchema:(SDMODataServiceDocument *)aService;

/**
 Static method that loads all of the entity type property labels.
 This method is called when the sapsopaServiceV0 class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadLabels:(SDMODataServiceDocument *)aService;

/**
 Static method that returns the label for a given property name.
 @param aPropertyName Property name.
 @return Property label.
*/
+ (NSString *)getLabelForProperty:(NSString *)aPropertyName;


#pragma mark Entity Navigation Property loading methods
/**
 Navigation property. Loads reportview details for this entity from the provided data.
 @param aData The NSData containing the reportview information to be parsed.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns YES if the method completed successfully.
*/
- (BOOL)loadReportviewWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Navigation property. Loads reportviewfilters details for this entity from the provided data.
 @param aData The NSData containing the reportviewfilters information to be parsed.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns YES if the method completed successfully.
*/
- (BOOL)loadReportviewfiltersWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;


@end

#pragma mark - reportpagelayoutTypeV0
@interface reportpagelayoutTypeV0 : BaseEntityType 

@property (strong, nonatomic) NSString *REPORTPAGEID; ///< REPORTPAGEID - Edm.String
@property (strong, nonatomic) NSNumber *ROWNUMBER; ///< ROWNUMBER - Edm.Byte
@property (strong, nonatomic) NSNumber *COLUMNNUMBER; ///< COLUMNNUMBER - Edm.Byte
@property (strong, nonatomic) NSString *REPORTID; ///< REPORTID - Edm.String
@property (strong, nonatomic) NSString *REPORTVIEWNAME; ///< REPORTVIEWNAME - Edm.String
@property (strong, nonatomic) NSString *REPORTVIEWID; ///< REPORTVIEWID - Edm.String
@property (strong, nonatomic) NSString *REPORTVIEWTYPE; ///< REPORTVIEWTYPE - Edm.String
@property (strong, nonatomic) NSNumber *ROWSPAN; ///< ROWSPAN - Edm.Byte
@property (strong, nonatomic) NSNumber *COLUMNSPAN; ///< COLUMNSPAN - Edm.Byte
@property (strong, nonatomic) NSString *LEGENDPOSITION; ///< LEGENDPOSITION - Edm.String
@property (strong, nonatomic) NSString *DISPLAYLEGEND; ///< DISPLAYLEGEND - Edm.String
#pragma mark Entity Navigation Properties
@property (strong, nonatomic) ODataQuery *reportviewQuery;
@property (strong, nonatomic) NSMutableArray *reportview;

#pragma mark Static Methods
/**
 Static method that returns an array of reportpagelayoutTypeV0 entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to reportpagelayoutTypeV0 entities.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of reportpagelayoutTypeV0 entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseReportpagelayoutTypeEntriesWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of reportpagelayoutTypeV0 entities and their related entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to reportpagelayoutTypeV0 entities.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of reportpagelayoutTypeV0 entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseExpandedReportpagelayoutTypeEntriesWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Returns a single reportpagelayoutTypeV0 entity from the provided data.
 @param aData The NSData containing an Atom Entry including the entry to be parsed to a reportpagelayoutTypeV0 entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a reportpagelayoutTypeV0 entity. Returns nil if the data in invalid.
*/
+ (reportpagelayoutTypeV0 *)parseReportpagelayoutTypeEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns a single reportpagelayoutTypeV0 entity and related entities from the provided data.
 @param aData The NSData containing an Atom Entry including the entry and its related entries to be parsed to a reportpagelayoutTypeV0 entity.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a reportpagelayoutTypeV0 entity. Returns nil if the data in invalid.
*/
+ (reportpagelayoutTypeV0 *)parseExpandedReportpagelayoutTypeEntryWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of reportpagelayoutTypeV0 objects from a given array of SDMODataEntry objects.
 @param sdmEntries Array of SDMODataEntry objects.
 @return Array of reportpagelayoutTypeV0 objects.
*/
+ (NSMutableArray *)createReportpagelayoutTypeEntriesForSDMEntries:(NSMutableArray *)sdmEntries;

/**
 Static method that loads the entity schema of this type.
 This method is called when the sapsopaServiceV0 class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadEntitySchema:(SDMODataServiceDocument *)aService;

/**
 Static method that loads all of the entity type property labels.
 This method is called when the sapsopaServiceV0 class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadLabels:(SDMODataServiceDocument *)aService;

/**
 Static method that returns the label for a given property name.
 @param aPropertyName Property name.
 @return Property label.
*/
+ (NSString *)getLabelForProperty:(NSString *)aPropertyName;


#pragma mark Entity Navigation Property loading methods
/**
 Navigation property. Loads reportview details for this entity from the provided data.
 @param aData The NSData containing the reportview information to be parsed.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns YES if the method completed successfully.
*/
- (BOOL)loadReportviewWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;


@end

#pragma mark - reportviewTypeV0
@interface reportviewTypeV0 : BaseEntityType 

@property (strong, nonatomic) NSString *REPORTID; ///< REPORTID - Edm.String
@property (strong, nonatomic) NSString *REPORTVIEWID; ///< REPORTVIEWID - Edm.String
@property (strong, nonatomic) NSString *ATTR_ID; ///< ATTR_ID - Edm.String
@property (strong, nonatomic) NSString *ATTR_NAME; ///< ATTR_NAME - Edm.String
@property (strong, nonatomic) NSString *ATTR_TYPE; ///< ATTR_TYPE - Edm.String
@property (strong, nonatomic) NSNumber *SEQUENCE; ///< SEQUENCE - Edm.Byte

#pragma mark Static Methods
/**
 Static method that returns an array of reportviewTypeV0 entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to reportviewTypeV0 entities.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of reportviewTypeV0 entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseReportviewTypeEntriesWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of reportviewTypeV0 entities and their related entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to reportviewTypeV0 entities.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of reportviewTypeV0 entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseExpandedReportviewTypeEntriesWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Returns a single reportviewTypeV0 entity from the provided data.
 @param aData The NSData containing an Atom Entry including the entry to be parsed to a reportviewTypeV0 entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a reportviewTypeV0 entity. Returns nil if the data in invalid.
*/
+ (reportviewTypeV0 *)parseReportviewTypeEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns a single reportviewTypeV0 entity and related entities from the provided data.
 @param aData The NSData containing an Atom Entry including the entry and its related entries to be parsed to a reportviewTypeV0 entity.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a reportviewTypeV0 entity. Returns nil if the data in invalid.
*/
+ (reportviewTypeV0 *)parseExpandedReportviewTypeEntryWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of reportviewTypeV0 objects from a given array of SDMODataEntry objects.
 @param sdmEntries Array of SDMODataEntry objects.
 @return Array of reportviewTypeV0 objects.
*/
+ (NSMutableArray *)createReportviewTypeEntriesForSDMEntries:(NSMutableArray *)sdmEntries;

/**
 Static method that loads the entity schema of this type.
 This method is called when the sapsopaServiceV0 class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadEntitySchema:(SDMODataServiceDocument *)aService;

/**
 Static method that loads all of the entity type property labels.
 This method is called when the sapsopaServiceV0 class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadLabels:(SDMODataServiceDocument *)aService;

/**
 Static method that returns the label for a given property name.
 @param aPropertyName Property name.
 @return Property label.
*/
+ (NSString *)getLabelForProperty:(NSString *)aPropertyName;



@end

#pragma mark - reportTypeV0
@interface reportTypeV0 : BaseEntityType 

@property (strong, nonatomic) NSString *REPORTID; ///< REPORTID - Edm.String
@property (strong, nonatomic) NSString *ATTR_ID; ///< ATTR_ID - Edm.String
@property (strong, nonatomic) NSString *ATTR_NAME; ///< ATTR_NAME - Edm.String
@property (strong, nonatomic) NSString *ATTR_TYPE; ///< ATTR_TYPE - Edm.String
@property (strong, nonatomic) NSString *PLAN_OBJECT; ///< PLAN_OBJECT - Edm.String
@property (strong, nonatomic) NSString *PLAN_OBJECT_DESCR; ///< PLAN_OBJECT_DESCR - Edm.String

#pragma mark Static Methods
/**
 Static method that returns an array of reportTypeV0 entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to reportTypeV0 entities.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of reportTypeV0 entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseReportTypeEntriesWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of reportTypeV0 entities and their related entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to reportTypeV0 entities.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of reportTypeV0 entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseExpandedReportTypeEntriesWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Returns a single reportTypeV0 entity from the provided data.
 @param aData The NSData containing an Atom Entry including the entry to be parsed to a reportTypeV0 entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a reportTypeV0 entity. Returns nil if the data in invalid.
*/
+ (reportTypeV0 *)parseReportTypeEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns a single reportTypeV0 entity and related entities from the provided data.
 @param aData The NSData containing an Atom Entry including the entry and its related entries to be parsed to a reportTypeV0 entity.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a reportTypeV0 entity. Returns nil if the data in invalid.
*/
+ (reportTypeV0 *)parseExpandedReportTypeEntryWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of reportTypeV0 objects from a given array of SDMODataEntry objects.
 @param sdmEntries Array of SDMODataEntry objects.
 @return Array of reportTypeV0 objects.
*/
+ (NSMutableArray *)createReportTypeEntriesForSDMEntries:(NSMutableArray *)sdmEntries;

/**
 Static method that loads the entity schema of this type.
 This method is called when the sapsopaServiceV0 class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadEntitySchema:(SDMODataServiceDocument *)aService;

/**
 Static method that loads all of the entity type property labels.
 This method is called when the sapsopaServiceV0 class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadLabels:(SDMODataServiceDocument *)aService;

/**
 Static method that returns the label for a given property name.
 @param aPropertyName Property name.
 @return Property label.
*/
+ (NSString *)getLabelForProperty:(NSString *)aPropertyName;



@end

#pragma mark - reportviewfiltersTypeV0
@interface reportviewfiltersTypeV0 : BaseEntityType 

@property (strong, nonatomic) NSString *REPORTVIEWID; ///< REPORTVIEWID - Edm.String
@property (strong, nonatomic) NSString *OPERATOR; ///< OPERATOR - Edm.String
@property (strong, nonatomic) NSString *ATTR; ///< ATTR - Edm.String
@property (strong, nonatomic) NSString *ATTR_VAL; ///< ATTR_VAL - Edm.String

#pragma mark Static Methods
/**
 Static method that returns an array of reportviewfiltersTypeV0 entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to reportviewfiltersTypeV0 entities.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of reportviewfiltersTypeV0 entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseReportviewfiltersTypeEntriesWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of reportviewfiltersTypeV0 entities and their related entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to reportviewfiltersTypeV0 entities.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of reportviewfiltersTypeV0 entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseExpandedReportviewfiltersTypeEntriesWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Returns a single reportviewfiltersTypeV0 entity from the provided data.
 @param aData The NSData containing an Atom Entry including the entry to be parsed to a reportviewfiltersTypeV0 entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a reportviewfiltersTypeV0 entity. Returns nil if the data in invalid.
*/
+ (reportviewfiltersTypeV0 *)parseReportviewfiltersTypeEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns a single reportviewfiltersTypeV0 entity and related entities from the provided data.
 @param aData The NSData containing an Atom Entry including the entry and its related entries to be parsed to a reportviewfiltersTypeV0 entity.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a reportviewfiltersTypeV0 entity. Returns nil if the data in invalid.
*/
+ (reportviewfiltersTypeV0 *)parseExpandedReportviewfiltersTypeEntryWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of reportviewfiltersTypeV0 objects from a given array of SDMODataEntry objects.
 @param sdmEntries Array of SDMODataEntry objects.
 @return Array of reportviewfiltersTypeV0 objects.
*/
+ (NSMutableArray *)createReportviewfiltersTypeEntriesForSDMEntries:(NSMutableArray *)sdmEntries;

/**
 Static method that loads the entity schema of this type.
 This method is called when the sapsopaServiceV0 class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadEntitySchema:(SDMODataServiceDocument *)aService;

/**
 Static method that loads all of the entity type property labels.
 This method is called when the sapsopaServiceV0 class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadLabels:(SDMODataServiceDocument *)aService;

/**
 Static method that returns the label for a given property name.
 @param aPropertyName Property name.
 @return Property label.
*/
+ (NSString *)getLabelForProperty:(NSString *)aPropertyName;



@end



#pragma mark - sapsopaV0 Service Proxy
@interface sapsopaServiceV0 : BaseServiceObject

#pragma mark Query properties for service Entity Sets
/**
The OData query for the reportsType collection.
(Addressable true, Requires-filter false, Creatable true, Updatable true, Deletable true)
*/
@property (strong, nonatomic) ODataQuery *reportsQuery;

/**
The OData query for the reportpagesType collection.
(Addressable true, Requires-filter false, Creatable true, Updatable true, Deletable true)
*/
@property (strong, nonatomic) ODataQuery *reportpagesQuery;

/**
The OData query for the reportviewsType collection.
(Addressable true, Requires-filter false, Creatable true, Updatable true, Deletable true)
*/
@property (strong, nonatomic) ODataQuery *reportviewsQuery;

/**
The OData query for the reportpagelayoutType collection.
(Addressable true, Requires-filter false, Creatable true, Updatable true, Deletable true)
*/
@property (strong, nonatomic) ODataQuery *reportpagelayoutQuery;

/**
The OData query for the reportviewType collection.
(Addressable true, Requires-filter false, Creatable true, Updatable true, Deletable true)
*/
@property (strong, nonatomic) ODataQuery *reportviewQuery;

/**
The OData query for the reportType collection.
(Addressable true, Requires-filter false, Creatable true, Updatable true, Deletable true)
*/
@property (strong, nonatomic) ODataQuery *reportQuery;

/**
The OData query for the reportviewfiltersType collection.
(Addressable true, Requires-filter false, Creatable true, Updatable true, Deletable true)
*/
@property (strong, nonatomic) ODataQuery *reportviewfiltersQuery;


#pragma mark Service Entity Set methods
/**
 Returns a collection of reportsTypeV0 entities from the data returned by the OData service.
 @param aData The NSData returned from the OData service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of reportsTypeV0 entities.
*/
- (NSMutableArray *)getReportsWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns the OData query for a specific reportsTypeV0 entity.
 @param REPORTID Part of the reportsTypeV0 unique identifier (of type Edm.String).
 Note: pass the parameter values exactly as they should appear in the query URL, 
 in the correct format according to their types 
 (for more information, see: http://www.odata.org/documentation/overview#AbstractTypeSystem).
 @return Returns an OData query object.
*/
- (ODataQuery *)getReportsEntryQueryWithREPORTID:(NSString *)REPORTID;

/**
 Returns the OData query for a specific reportsTypeV0 entity with typed parameters.
 Note: This method is relevant only for OData compliant services.
 @param REPORTID Part of the reportsTypeV0 unique identifier (of type Edm.String).
 @return Returns an OData query object.
*/
- (ODataQuery *)getReportsEntryQueryTypedWithREPORTID:(NSString *)REPORTID;

/**
 Returns a specific reportsTypeV0 entity from the provided data.
 @param aData The NSData containing the reportsTypeV0 information to be parsed to a reportsTypeV0 entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a reportsTypeV0 entity. Returns nil if the data in invalid.
*/
- (reportsTypeV0 *)getReportsEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;
/**
 Returns a collection of reportpagesTypeV0 entities from the data returned by the OData service.
 @param aData The NSData returned from the OData service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of reportpagesTypeV0 entities.
*/
- (NSMutableArray *)getReportpagesWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns the OData query for a specific reportpagesTypeV0 entity.
 @param REPORTPAGEID Part of the reportpagesTypeV0 unique identifier (of type Edm.String).
 Note: pass the parameter values exactly as they should appear in the query URL, 
 in the correct format according to their types 
 (for more information, see: http://www.odata.org/documentation/overview#AbstractTypeSystem).
 @return Returns an OData query object.
*/
- (ODataQuery *)getReportpagesEntryQueryWithREPORTPAGEID:(NSString *)REPORTPAGEID;

/**
 Returns the OData query for a specific reportpagesTypeV0 entity with typed parameters.
 Note: This method is relevant only for OData compliant services.
 @param REPORTPAGEID Part of the reportpagesTypeV0 unique identifier (of type Edm.String).
 @return Returns an OData query object.
*/
- (ODataQuery *)getReportpagesEntryQueryTypedWithREPORTPAGEID:(NSString *)REPORTPAGEID;

/**
 Returns a specific reportpagesTypeV0 entity from the provided data.
 @param aData The NSData containing the reportpagesTypeV0 information to be parsed to a reportpagesTypeV0 entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a reportpagesTypeV0 entity. Returns nil if the data in invalid.
*/
- (reportpagesTypeV0 *)getReportpagesEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;
/**
 Returns a collection of reportviewsTypeV0 entities from the data returned by the OData service.
 @param aData The NSData returned from the OData service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of reportviewsTypeV0 entities.
*/
- (NSMutableArray *)getReportviewsWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns the OData query for a specific reportviewsTypeV0 entity.
 @param REPORTVIEWID Part of the reportviewsTypeV0 unique identifier (of type Edm.String).
 Note: pass the parameter values exactly as they should appear in the query URL, 
 in the correct format according to their types 
 (for more information, see: http://www.odata.org/documentation/overview#AbstractTypeSystem).
 @return Returns an OData query object.
*/
- (ODataQuery *)getReportviewsEntryQueryWithREPORTVIEWID:(NSString *)REPORTVIEWID;

/**
 Returns the OData query for a specific reportviewsTypeV0 entity with typed parameters.
 Note: This method is relevant only for OData compliant services.
 @param REPORTVIEWID Part of the reportviewsTypeV0 unique identifier (of type Edm.String).
 @return Returns an OData query object.
*/
- (ODataQuery *)getReportviewsEntryQueryTypedWithREPORTVIEWID:(NSString *)REPORTVIEWID;

/**
 Returns a specific reportviewsTypeV0 entity from the provided data.
 @param aData The NSData containing the reportviewsTypeV0 information to be parsed to a reportviewsTypeV0 entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a reportviewsTypeV0 entity. Returns nil if the data in invalid.
*/
- (reportviewsTypeV0 *)getReportviewsEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;
/**
 Returns a collection of reportpagelayoutTypeV0 entities from the data returned by the OData service.
 @param aData The NSData returned from the OData service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of reportpagelayoutTypeV0 entities.
*/
- (NSMutableArray *)getReportpagelayoutWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns the OData query for a specific reportpagelayoutTypeV0 entity.
 @param REPORTPAGEID Part of the reportpagelayoutTypeV0 unique identifier (of type Edm.String).
 @param ROWNUMBER Part of the reportpagelayoutTypeV0 unique identifier (of type Edm.Byte).
 @param COLUMNNUMBER Part of the reportpagelayoutTypeV0 unique identifier (of type Edm.Byte).
 Note: pass the parameter values exactly as they should appear in the query URL, 
 in the correct format according to their types 
 (for more information, see: http://www.odata.org/documentation/overview#AbstractTypeSystem).
 @return Returns an OData query object.
*/
- (ODataQuery *)getReportpagelayoutEntryQueryWithREPORTPAGEID:(NSString *)REPORTPAGEID andROWNUMBER:(NSString *)ROWNUMBER andCOLUMNNUMBER:(NSString *)COLUMNNUMBER;

/**
 Returns the OData query for a specific reportpagelayoutTypeV0 entity with typed parameters.
 Note: This method is relevant only for OData compliant services.
 @param REPORTPAGEID Part of the reportpagelayoutTypeV0 unique identifier (of type Edm.String).
 @param ROWNUMBER Part of the reportpagelayoutTypeV0 unique identifier (of type Edm.Byte).
 @param COLUMNNUMBER Part of the reportpagelayoutTypeV0 unique identifier (of type Edm.Byte).
 @return Returns an OData query object.
*/
- (ODataQuery *)getReportpagelayoutEntryQueryTypedWithREPORTPAGEID:(NSString *)REPORTPAGEID andROWNUMBER:(NSNumber *)ROWNUMBER andCOLUMNNUMBER:(NSNumber *)COLUMNNUMBER;

/**
 Returns a specific reportpagelayoutTypeV0 entity from the provided data.
 @param aData The NSData containing the reportpagelayoutTypeV0 information to be parsed to a reportpagelayoutTypeV0 entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a reportpagelayoutTypeV0 entity. Returns nil if the data in invalid.
*/
- (reportpagelayoutTypeV0 *)getReportpagelayoutEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;
/**
 Returns a collection of reportviewTypeV0 entities from the data returned by the OData service.
 @param aData The NSData returned from the OData service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of reportviewTypeV0 entities.
*/
- (NSMutableArray *)getReportviewWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns the OData query for a specific reportviewTypeV0 entity.
 @param REPORTVIEWID Part of the reportviewTypeV0 unique identifier (of type Edm.String).
 @param ATTR_ID Part of the reportviewTypeV0 unique identifier (of type Edm.String).
 Note: pass the parameter values exactly as they should appear in the query URL, 
 in the correct format according to their types 
 (for more information, see: http://www.odata.org/documentation/overview#AbstractTypeSystem).
 @return Returns an OData query object.
*/
- (ODataQuery *)getReportviewEntryQueryWithREPORTVIEWID:(NSString *)REPORTVIEWID andATTR_ID:(NSString *)ATTR_ID;

/**
 Returns the OData query for a specific reportviewTypeV0 entity with typed parameters.
 Note: This method is relevant only for OData compliant services.
 @param REPORTVIEWID Part of the reportviewTypeV0 unique identifier (of type Edm.String).
 @param ATTR_ID Part of the reportviewTypeV0 unique identifier (of type Edm.String).
 @return Returns an OData query object.
*/
- (ODataQuery *)getReportviewEntryQueryTypedWithREPORTVIEWID:(NSString *)REPORTVIEWID andATTR_ID:(NSString *)ATTR_ID;

/**
 Returns a specific reportviewTypeV0 entity from the provided data.
 @param aData The NSData containing the reportviewTypeV0 information to be parsed to a reportviewTypeV0 entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a reportviewTypeV0 entity. Returns nil if the data in invalid.
*/
- (reportviewTypeV0 *)getReportviewEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;
/**
 Returns a collection of reportTypeV0 entities from the data returned by the OData service.
 @param aData The NSData returned from the OData service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of reportTypeV0 entities.
*/
- (NSMutableArray *)getReportWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns the OData query for a specific reportTypeV0 entity.
 @param REPORTID Part of the reportTypeV0 unique identifier (of type Edm.String).
 @param ATTR_ID Part of the reportTypeV0 unique identifier (of type Edm.String).
 Note: pass the parameter values exactly as they should appear in the query URL, 
 in the correct format according to their types 
 (for more information, see: http://www.odata.org/documentation/overview#AbstractTypeSystem).
 @return Returns an OData query object.
*/
- (ODataQuery *)getReportEntryQueryWithREPORTID:(NSString *)REPORTID andATTR_ID:(NSString *)ATTR_ID;

/**
 Returns the OData query for a specific reportTypeV0 entity with typed parameters.
 Note: This method is relevant only for OData compliant services.
 @param REPORTID Part of the reportTypeV0 unique identifier (of type Edm.String).
 @param ATTR_ID Part of the reportTypeV0 unique identifier (of type Edm.String).
 @return Returns an OData query object.
*/
- (ODataQuery *)getReportEntryQueryTypedWithREPORTID:(NSString *)REPORTID andATTR_ID:(NSString *)ATTR_ID;

/**
 Returns a specific reportTypeV0 entity from the provided data.
 @param aData The NSData containing the reportTypeV0 information to be parsed to a reportTypeV0 entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a reportTypeV0 entity. Returns nil if the data in invalid.
*/
- (reportTypeV0 *)getReportEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;
/**
 Returns a collection of reportviewfiltersTypeV0 entities from the data returned by the OData service.
 @param aData The NSData returned from the OData service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of reportviewfiltersTypeV0 entities.
*/
- (NSMutableArray *)getReportviewfiltersWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns the OData query for a specific reportviewfiltersTypeV0 entity.
 @param REPORTVIEWID Part of the reportviewfiltersTypeV0 unique identifier (of type Edm.String).
 @param OPERATOR Part of the reportviewfiltersTypeV0 unique identifier (of type Edm.String).
 @param ATTR Part of the reportviewfiltersTypeV0 unique identifier (of type Edm.String).
 @param ATTR_VAL Part of the reportviewfiltersTypeV0 unique identifier (of type Edm.String).
 Note: pass the parameter values exactly as they should appear in the query URL, 
 in the correct format according to their types 
 (for more information, see: http://www.odata.org/documentation/overview#AbstractTypeSystem).
 @return Returns an OData query object.
*/
- (ODataQuery *)getReportviewfiltersEntryQueryWithREPORTVIEWID:(NSString *)REPORTVIEWID andOPERATOR:(NSString *)OPERATOR andATTR:(NSString *)ATTR andATTR_VAL:(NSString *)ATTR_VAL;

/**
 Returns the OData query for a specific reportviewfiltersTypeV0 entity with typed parameters.
 Note: This method is relevant only for OData compliant services.
 @param REPORTVIEWID Part of the reportviewfiltersTypeV0 unique identifier (of type Edm.String).
 @param OPERATOR Part of the reportviewfiltersTypeV0 unique identifier (of type Edm.String).
 @param ATTR Part of the reportviewfiltersTypeV0 unique identifier (of type Edm.String).
 @param ATTR_VAL Part of the reportviewfiltersTypeV0 unique identifier (of type Edm.String).
 @return Returns an OData query object.
*/
- (ODataQuery *)getReportviewfiltersEntryQueryTypedWithREPORTVIEWID:(NSString *)REPORTVIEWID andOPERATOR:(NSString *)OPERATOR andATTR:(NSString *)ATTR andATTR_VAL:(NSString *)ATTR_VAL;

/**
 Returns a specific reportviewfiltersTypeV0 entity from the provided data.
 @param aData The NSData containing the reportviewfiltersTypeV0 information to be parsed to a reportviewfiltersTypeV0 entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a reportviewfiltersTypeV0 entity. Returns nil if the data in invalid.
*/
- (reportviewfiltersTypeV0 *)getReportviewfiltersEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;


#pragma mark Service Function Import methods
@end