/*
 
 Auto-Generated by SAP NetWeaver Gateway Productivity Accelerator, Version 1.0
 
 File: sapsopaServiceDeclarations.h
 Abstract: Aliases for the generated proxy class names of the sapsopa service.
   
*/

#import <Foundation/Foundation.h>
#import "sapsopaServiceV0.h"

@compatibility_alias sapsopaService sapsopaServiceV0;
@compatibility_alias reportsType reportsTypeV0;
@compatibility_alias reportpagesType reportpagesTypeV0;
@compatibility_alias reportviewsType reportviewsTypeV0;
@compatibility_alias reportpagelayoutType reportpagelayoutTypeV0;
@compatibility_alias reportviewType reportviewTypeV0;
@compatibility_alias reportType reportTypeV0;
@compatibility_alias reportviewfiltersType reportviewfiltersTypeV0;
