/*
 
 Auto-Generated by SAP NetWeaver Gateway Productivity Accelerator, Version 1.1.1
 
 File: sapsopaServiceDeclarations.h
 Abstract: Aliases for the generated proxy class names of the sapsopa service.
   
*/

#import <Foundation/Foundation.h>
#import "sapsopaServiceV0.h"

@compatibility_alias sapsopaService sapsopaServiceV0;
@compatibility_alias excludecharsType excludecharsTypeV0;
@compatibility_alias reportpagedefaultType reportpagedefaultTypeV0;
@compatibility_alias reportsType reportsTypeV0;
@compatibility_alias reportpagesType reportpagesTypeV0;
@compatibility_alias reportviewsType reportviewsTypeV0;
@compatibility_alias reportpagelayoutType reportpagelayoutTypeV0;
@compatibility_alias reportviewType reportviewTypeV0;
@compatibility_alias reportType reportTypeV0;
@compatibility_alias reportqueryconstraintsType reportqueryconstraintsTypeV0;
@compatibility_alias reportviewsfilterType reportviewsfilterTypeV0;
@compatibility_alias sharedobjectsType sharedobjectsTypeV0;
@compatibility_alias reportpagenavType reportpagenavTypeV0;
@compatibility_alias reportviewpagesType reportviewpagesTypeV0;
@compatibility_alias reportviewwbfavType reportviewwbfavTypeV0;
